version: "3"
services:
  db:
    image: "postgres:11.2-alpine"
    container_name: "postgres-test"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vending_machine

  flyway:
    image: "boxfuse/flyway:5.2.4"
    volumes:
    - ./docker/flyway/db/migration:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/vending_machine -user=postgres -password=password -connectRetries=60 migrate
    depends_on:
    - db